CREATE TABLE IF NOT EXISTS campaigns(code TEXT PRIMARY KEY,name TEXT NOT NULL,end_date TEXT NOT NULL,url TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1,sort_order INTEGER NOT NULL DEFAULT 0,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);
INSERT OR IGNORE INTO settings VALUES('columns','3');
